//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangoteSAP3.DangoteCustomerDetailsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", ConfigurationName="DangoteCustomerDetailsService.si_atm_cust_abs_sync")]
    public interface si_atm_cust_abs_sync {
        
        // CODEGEN: Generating message contract since the operation si_atm_cust_abs_sync is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse si_atm_cust_abs_sync(DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse> si_atm_cust_abs_syncAsync(DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_cust_in : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comp_codeField;
        
        private string cust_numField;
        
        private string cc_areaField;
        
        private string sales_orgField;
        
        private string exportField;
        
        private string access_tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comp_code {
            get {
                return this.comp_codeField;
            }
            set {
                this.comp_codeField = value;
                this.RaisePropertyChanged("comp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cust_num {
            get {
                return this.cust_numField;
            }
            set {
                this.cust_numField = value;
                this.RaisePropertyChanged("cust_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cc_area {
            get {
                return this.cc_areaField;
            }
            set {
                this.cc_areaField = value;
                this.RaisePropertyChanged("cc_area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sales_org {
            get {
                return this.sales_orgField;
            }
            set {
                this.sales_orgField = value;
                this.RaisePropertyChanged("sales_org");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string export {
            get {
                return this.exportField;
            }
            set {
                this.exportField = value;
                this.RaisePropertyChanged("export");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_cust_out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cust_nameField;
        
        private string addressField;
        
        private string countryField;
        
        private string regionField;
        
        private string exposureField;
        
        private string divisionField;
        
        private dt_atm_cust_outLines[] error_logField;
        
        private string access_tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cust_name {
            get {
                return this.cust_nameField;
            }
            set {
                this.cust_nameField = value;
                this.RaisePropertyChanged("cust_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string exposure {
            get {
                return this.exposureField;
            }
            set {
                this.exposureField = value;
                this.RaisePropertyChanged("exposure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_atm_cust_outLines[] error_log {
            get {
                return this.error_logField;
            }
            set {
                this.error_logField = value;
                this.RaisePropertyChanged("error_log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_cust_outLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_atm_cust_abs_syncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", Order=0)]
        public DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_in mt_atm_cust_in;
        
        public si_atm_cust_abs_syncRequest() {
        }
        
        public si_atm_cust_abs_syncRequest(DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_in mt_atm_cust_in) {
            this.mt_atm_cust_in = mt_atm_cust_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_atm_cust_abs_syncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", Order=0)]
        public DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_out mt_atm_cust_out;
        
        public si_atm_cust_abs_syncResponse() {
        }
        
        public si_atm_cust_abs_syncResponse(DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_out mt_atm_cust_out) {
            this.mt_atm_cust_out = mt_atm_cust_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface si_atm_cust_abs_syncChannel : DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class si_atm_cust_abs_syncClient : System.ServiceModel.ClientBase<DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync>, DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync {
        
        public si_atm_cust_abs_syncClient() {
        }
        
        public si_atm_cust_abs_syncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public si_atm_cust_abs_syncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_atm_cust_abs_syncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_atm_cust_abs_syncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync.si_atm_cust_abs_sync(DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest request) {
            return base.Channel.si_atm_cust_abs_sync(request);
        }
        
        public DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_out si_atm_cust_abs_sync(DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_in mt_atm_cust_in) {
            DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest inValue = new DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest();
            inValue.mt_atm_cust_in = mt_atm_cust_in;
            DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse retVal = ((DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync)(this)).si_atm_cust_abs_sync(inValue);
            return retVal.mt_atm_cust_out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse> DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync.si_atm_cust_abs_syncAsync(DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest request) {
            return base.Channel.si_atm_cust_abs_syncAsync(request);
        }
        
        public System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncResponse> si_atm_cust_abs_syncAsync(DangoteSAP3.DangoteCustomerDetailsService.dt_atm_cust_in mt_atm_cust_in) {
            DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest inValue = new DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_syncRequest();
            inValue.mt_atm_cust_in = mt_atm_cust_in;
            return ((DangoteSAP3.DangoteCustomerDetailsService.si_atm_cust_abs_sync)(this)).si_atm_cust_abs_syncAsync(inValue);
        }
    }
}
