//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangoteSAP3.DangoteOrderDownPaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", ConfigurationName="DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync")]
    public interface si_atm_dp_bapi_abs_sync {
        
        // CODEGEN: Generating message contract since the operation si_atm_dp_bapi_abs_sync is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse si_atm_dp_bapi_abs_sync(DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse> si_atm_dp_bapi_abs_syncAsync(DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_dp_in : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cust_numField;
        
        private string access_tokenField;
        
        private string comp_codeField;
        
        private string banknField;
        
        private string amountField;
        
        private string teller_noField;
        
        private string sales_orgField;
        
        private string plantField;
        
        private string split_typeField;
        
        private string delv_statusField;
        
        private string dest_regionField;
        
        private string receiver_nameField;
        
        private string dest_addressField;
        
        private string dest_cityField;
        
        private string dest_countryField;
        
        private string order_amountField;
        
        private string tran_idField;
        
        private string currencyField;
        
        private dt_atm_dp_inItem[] materialField;
        
        private dt_atm_dp_inLines[] quantityField;
        
        private dt_atm_dp_inLines1[] split_quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cust_num {
            get {
                return this.cust_numField;
            }
            set {
                this.cust_numField = value;
                this.RaisePropertyChanged("cust_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comp_code {
            get {
                return this.comp_codeField;
            }
            set {
                this.comp_codeField = value;
                this.RaisePropertyChanged("comp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bankn {
            get {
                return this.banknField;
            }
            set {
                this.banknField = value;
                this.RaisePropertyChanged("bankn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string teller_no {
            get {
                return this.teller_noField;
            }
            set {
                this.teller_noField = value;
                this.RaisePropertyChanged("teller_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sales_org {
            get {
                return this.sales_orgField;
            }
            set {
                this.sales_orgField = value;
                this.RaisePropertyChanged("sales_org");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string split_type {
            get {
                return this.split_typeField;
            }
            set {
                this.split_typeField = value;
                this.RaisePropertyChanged("split_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string delv_status {
            get {
                return this.delv_statusField;
            }
            set {
                this.delv_statusField = value;
                this.RaisePropertyChanged("delv_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dest_region {
            get {
                return this.dest_regionField;
            }
            set {
                this.dest_regionField = value;
                this.RaisePropertyChanged("dest_region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string receiver_name {
            get {
                return this.receiver_nameField;
            }
            set {
                this.receiver_nameField = value;
                this.RaisePropertyChanged("receiver_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string dest_address {
            get {
                return this.dest_addressField;
            }
            set {
                this.dest_addressField = value;
                this.RaisePropertyChanged("dest_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string dest_city {
            get {
                return this.dest_cityField;
            }
            set {
                this.dest_cityField = value;
                this.RaisePropertyChanged("dest_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string dest_country {
            get {
                return this.dest_countryField;
            }
            set {
                this.dest_countryField = value;
                this.RaisePropertyChanged("dest_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string order_amount {
            get {
                return this.order_amountField;
            }
            set {
                this.order_amountField = value;
                this.RaisePropertyChanged("order_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string tran_id {
            get {
                return this.tran_idField;
            }
            set {
                this.tran_idField = value;
                this.RaisePropertyChanged("tran_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_atm_dp_inItem[] material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_atm_dp_inLines[] quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_atm_dp_inLines1[] split_quantity {
            get {
                return this.split_quantityField;
            }
            set {
                this.split_quantityField = value;
                this.RaisePropertyChanged("split_quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_dp_inItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string material_noField;
        
        private string material_txtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string material_no {
            get {
                return this.material_noField;
            }
            set {
                this.material_noField = value;
                this.RaisePropertyChanged("material_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string material_txt {
            get {
                return this.material_txtField;
            }
            set {
                this.material_txtField = value;
                this.RaisePropertyChanged("material_txt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dt_doc_outLines[] transaction_statusField;
        
        private dt_doc_outLines1[] parentField;
        
        private dt_doc_outLines2[] childField;
        
        private dt_doc_outLines3[] paymentField;
        
        private string barcode_string1Field;
        
        private string barcode_string2Field;
        
        private string access_tokenField;
        
        private string created_childrenField;
        
        private dt_doc_outLines4[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_doc_outLines[] transaction_status {
            get {
                return this.transaction_statusField;
            }
            set {
                this.transaction_statusField = value;
                this.RaisePropertyChanged("transaction_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_doc_outLines1[] parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
                this.RaisePropertyChanged("parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_doc_outLines2[] child {
            get {
                return this.childField;
            }
            set {
                this.childField = value;
                this.RaisePropertyChanged("child");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_doc_outLines3[] payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string barcode_string1 {
            get {
                return this.barcode_string1Field;
            }
            set {
                this.barcode_string1Field = value;
                this.RaisePropertyChanged("barcode_string1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string barcode_string2 {
            get {
                return this.barcode_string2Field;
            }
            set {
                this.barcode_string2Field = value;
                this.RaisePropertyChanged("barcode_string2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string created_children {
            get {
                return this.created_childrenField;
            }
            set {
                this.created_childrenField = value;
                this.RaisePropertyChanged("created_children");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_doc_outLines4[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_outLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentField;
        
        private string atcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string atc {
            get {
                return this.atcField;
            }
            set {
                this.atcField = value;
                this.RaisePropertyChanged("atc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_outLines1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string docnumField;
        
        private string doctypeField;
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string docnum {
            get {
                return this.docnumField;
            }
            set {
                this.docnumField = value;
                this.RaisePropertyChanged("docnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doctype {
            get {
                return this.doctypeField;
            }
            set {
                this.doctypeField = value;
                this.RaisePropertyChanged("doctype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_outLines2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string doc_numField;
        
        private string doc_typeField;
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string doc_num {
            get {
                return this.doc_numField;
            }
            set {
                this.doc_numField = value;
                this.RaisePropertyChanged("doc_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doc_type {
            get {
                return this.doc_typeField;
            }
            set {
                this.doc_typeField = value;
                this.RaisePropertyChanged("doc_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_outLines3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentField;
        
        private string fiscal_yrField;
        
        private string comp_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fiscal_yr {
            get {
                return this.fiscal_yrField;
            }
            set {
                this.fiscal_yrField = value;
                this.RaisePropertyChanged("fiscal_yr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comp_code {
            get {
                return this.comp_codeField;
            }
            set {
                this.comp_codeField = value;
                this.RaisePropertyChanged("comp_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_doc_outLines4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_dp_inLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postatctransaction")]
    public partial class dt_atm_dp_inLines1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_atm_dp_bapi_abs_syncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", Order=0)]
        public DangoteSAP3.DangoteOrderDownPaymentService.dt_atm_dp_in mt_atm_dp_in;
        
        public si_atm_dp_bapi_abs_syncRequest() {
        }
        
        public si_atm_dp_bapi_abs_syncRequest(DangoteSAP3.DangoteOrderDownPaymentService.dt_atm_dp_in mt_atm_dp_in) {
            this.mt_atm_dp_in = mt_atm_dp_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_atm_dp_bapi_abs_syncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postatctransaction", Order=0)]
        public DangoteSAP3.DangoteOrderDownPaymentService.dt_doc_out mt_doc_out;
        
        public si_atm_dp_bapi_abs_syncResponse() {
        }
        
        public si_atm_dp_bapi_abs_syncResponse(DangoteSAP3.DangoteOrderDownPaymentService.dt_doc_out mt_doc_out) {
            this.mt_doc_out = mt_doc_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface si_atm_dp_bapi_abs_syncChannel : DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class si_atm_dp_bapi_abs_syncClient : System.ServiceModel.ClientBase<DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync>, DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync {
        
        public si_atm_dp_bapi_abs_syncClient() {
        }
        
        public si_atm_dp_bapi_abs_syncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public si_atm_dp_bapi_abs_syncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_atm_dp_bapi_abs_syncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_atm_dp_bapi_abs_syncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync.si_atm_dp_bapi_abs_sync(DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest request) {
            return base.Channel.si_atm_dp_bapi_abs_sync(request);
        }
        
        public DangoteSAP3.DangoteOrderDownPaymentService.dt_doc_out si_atm_dp_bapi_abs_sync(DangoteSAP3.DangoteOrderDownPaymentService.dt_atm_dp_in mt_atm_dp_in) {
            DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest inValue = new DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest();
            inValue.mt_atm_dp_in = mt_atm_dp_in;
            DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse retVal = ((DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync)(this)).si_atm_dp_bapi_abs_sync(inValue);
            return retVal.mt_doc_out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse> DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync.si_atm_dp_bapi_abs_syncAsync(DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest request) {
            return base.Channel.si_atm_dp_bapi_abs_syncAsync(request);
        }
        
        public System.Threading.Tasks.Task<DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncResponse> si_atm_dp_bapi_abs_syncAsync(DangoteSAP3.DangoteOrderDownPaymentService.dt_atm_dp_in mt_atm_dp_in) {
            DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest inValue = new DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_syncRequest();
            inValue.mt_atm_dp_in = mt_atm_dp_in;
            return ((DangoteSAP3.DangoteOrderDownPaymentService.si_atm_dp_bapi_abs_sync)(this)).si_atm_dp_bapi_abs_syncAsync(inValue);
        }
    }
}
