//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangoteSAP3.DangoteCustomerDownPaymentATCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dangote-group.com:ng:isop:postdownpayment", ConfigurationName="DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2")]
    public interface si_bank_abs_syc_v2 {
        
        // CODEGEN: Generating message contract since the operation si_bank_abs_syc_v2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response si_bank_abs_syc_v2(DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response> si_bank_abs_syc_v2Async(DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postdownpayment")]
    public partial class dt_bank_in : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string access_tokenField;
        
        private string comp_codeField;
        
        private string plantField;
        
        private string banknField;
        
        private string cust_numberField;
        
        private string amountField;
        
        private string teller_noField;
        
        private string tran_idField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comp_code {
            get {
                return this.comp_codeField;
            }
            set {
                this.comp_codeField = value;
                this.RaisePropertyChanged("comp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bankn {
            get {
                return this.banknField;
            }
            set {
                this.banknField = value;
                this.RaisePropertyChanged("bankn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cust_number {
            get {
                return this.cust_numberField;
            }
            set {
                this.cust_numberField = value;
                this.RaisePropertyChanged("cust_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string teller_no {
            get {
                return this.teller_noField;
            }
            set {
                this.teller_noField = value;
                this.RaisePropertyChanged("teller_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tran_id {
            get {
                return this.tran_idField;
            }
            set {
                this.tran_idField = value;
                this.RaisePropertyChanged("tran_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:postdownpayment")]
    public partial class dt_bank_out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dt_bank_outLines[] eRRORField;
        
        private string output_string1Field;
        
        private string output_string2Field;
        
        private string docNumField;
        
        private string trans_idField;
        
        private string compCodeField;
        
        private string fiscalYrField;
        
        private string accessTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_bank_outLines[] ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string output_string1 {
            get {
                return this.output_string1Field;
            }
            set {
                this.output_string1Field = value;
                this.RaisePropertyChanged("output_string1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string output_string2 {
            get {
                return this.output_string2Field;
            }
            set {
                this.output_string2Field = value;
                this.RaisePropertyChanged("output_string2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DocNum {
            get {
                return this.docNumField;
            }
            set {
                this.docNumField = value;
                this.RaisePropertyChanged("DocNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
                this.RaisePropertyChanged("trans_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CompCode {
            get {
                return this.compCodeField;
            }
            set {
                this.compCodeField = value;
                this.RaisePropertyChanged("CompCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FiscalYr {
            get {
                return this.fiscalYrField;
            }
            set {
                this.fiscalYrField = value;
                this.RaisePropertyChanged("FiscalYr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:postdownpayment")]
    public partial class dt_bank_outLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_bank_abs_syc_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postdownpayment", Order=0)]
        public DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_in mt_bank_in;
        
        public si_bank_abs_syc_v2Request() {
        }
        
        public si_bank_abs_syc_v2Request(DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_in mt_bank_in) {
            this.mt_bank_in = mt_bank_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_bank_abs_syc_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:postdownpayment", Order=0)]
        public DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_out mt_bank_out;
        
        public si_bank_abs_syc_v2Response() {
        }
        
        public si_bank_abs_syc_v2Response(DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_out mt_bank_out) {
            this.mt_bank_out = mt_bank_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface si_bank_abs_syc_v2Channel : DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class si_bank_abs_syc_v2Client : System.ServiceModel.ClientBase<DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2>, DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2 {
        
        public si_bank_abs_syc_v2Client() {
        }
        
        public si_bank_abs_syc_v2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public si_bank_abs_syc_v2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_bank_abs_syc_v2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_bank_abs_syc_v2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2.si_bank_abs_syc_v2(DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request request) {
            return base.Channel.si_bank_abs_syc_v2(request);
        }
        
        public DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_out si_bank_abs_syc_v2(DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_in mt_bank_in) {
            DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request inValue = new DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request();
            inValue.mt_bank_in = mt_bank_in;
            DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response retVal = ((DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2)(this)).si_bank_abs_syc_v2(inValue);
            return retVal.mt_bank_out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response> DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2.si_bank_abs_syc_v2Async(DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request request) {
            return base.Channel.si_bank_abs_syc_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Response> si_bank_abs_syc_v2Async(DangoteSAP3.DangoteCustomerDownPaymentATCService.dt_bank_in mt_bank_in) {
            DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request inValue = new DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2Request();
            inValue.mt_bank_in = mt_bank_in;
            return ((DangoteSAP3.DangoteCustomerDownPaymentATCService.si_bank_abs_syc_v2)(this)).si_bank_abs_syc_v2Async(inValue);
        }
    }
}
