//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangoteSAP3.DangoteLoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", ConfigurationName="DangoteLoginService.si_full_auth_abs")]
    public interface si_full_auth_abs {
        
        // CODEGEN: Generating message contract since the operation si_full_auth_abs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DangoteSAP3.DangoteLoginService.si_full_auth_absResponse si_full_auth_abs(DangoteSAP3.DangoteLoginService.si_full_auth_absRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteLoginService.si_full_auth_absResponse> si_full_auth_absAsync(DangoteSAP3.DangoteLoginService.si_full_auth_absRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_in : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string full_synchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string full_synch {
            get {
                return this.full_synchField;
            }
            set {
                this.full_synchField = value;
                this.RaisePropertyChanged("full_synch");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authtokenField;
        
        private string logged_onField;
        
        private dt_full_auth_outLines[] error_logField;
        
        private dt_full_auth_outRecord[] recordsField;
        
        private dt_full_auth_outRegion[] regionsField;
        
        private dt_full_auth_outArea[] credit_areasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authtoken {
            get {
                return this.authtokenField;
            }
            set {
                this.authtokenField = value;
                this.RaisePropertyChanged("authtoken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string logged_on {
            get {
                return this.logged_onField;
            }
            set {
                this.logged_onField = value;
                this.RaisePropertyChanged("logged_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_full_auth_outLines[] error_log {
            get {
                return this.error_logField;
            }
            set {
                this.error_logField = value;
                this.RaisePropertyChanged("error_log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_full_auth_outRecord[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("region", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_full_auth_outRegion[] regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
                this.RaisePropertyChanged("regions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("area", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_full_auth_outArea[] credit_areas {
            get {
                return this.credit_areasField;
            }
            set {
                this.credit_areasField = value;
                this.RaisePropertyChanged("credit_areas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_outLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_outRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string company_codeField;
        
        private string company_code_descriptionField;
        
        private string sales_organisationField;
        
        private string sales_orgaisation_descriptionField;
        
        private string plantField;
        
        private string plant_descriptionField;
        
        private string materialField;
        
        private string material_descriptionField;
        
        private string sales_unitField;
        
        private string base_unitField;
        
        private string divisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string company_code {
            get {
                return this.company_codeField;
            }
            set {
                this.company_codeField = value;
                this.RaisePropertyChanged("company_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string company_code_description {
            get {
                return this.company_code_descriptionField;
            }
            set {
                this.company_code_descriptionField = value;
                this.RaisePropertyChanged("company_code_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sales_organisation {
            get {
                return this.sales_organisationField;
            }
            set {
                this.sales_organisationField = value;
                this.RaisePropertyChanged("sales_organisation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sales_orgaisation_description {
            get {
                return this.sales_orgaisation_descriptionField;
            }
            set {
                this.sales_orgaisation_descriptionField = value;
                this.RaisePropertyChanged("sales_orgaisation_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string plant_description {
            get {
                return this.plant_descriptionField;
            }
            set {
                this.plant_descriptionField = value;
                this.RaisePropertyChanged("plant_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string material_description {
            get {
                return this.material_descriptionField;
            }
            set {
                this.material_descriptionField = value;
                this.RaisePropertyChanged("material_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sales_unit {
            get {
                return this.sales_unitField;
            }
            set {
                this.sales_unitField = value;
                this.RaisePropertyChanged("sales_unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Base_unit {
            get {
                return this.base_unitField;
            }
            set {
                this.base_unitField = value;
                this.RaisePropertyChanged("Base_unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("division");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_outRegion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string country_codeField;
        
        private string region_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                this.country_codeField = value;
                this.RaisePropertyChanged("country_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string region_name {
            get {
                return this.region_nameField;
            }
            set {
                this.region_nameField = value;
                this.RaisePropertyChanged("region_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_full_auth_outArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string company_codeField;
        
        private string cbn_codeField;
        
        private string credit_areaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string company_code {
            get {
                return this.company_codeField;
            }
            set {
                this.company_codeField = value;
                this.RaisePropertyChanged("company_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cbn_code {
            get {
                return this.cbn_codeField;
            }
            set {
                this.cbn_codeField = value;
                this.RaisePropertyChanged("cbn_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string credit_area {
            get {
                return this.credit_areaField;
            }
            set {
                this.credit_areaField = value;
                this.RaisePropertyChanged("credit_area");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_full_auth_absRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", Order=0)]
        public DangoteSAP3.DangoteLoginService.dt_full_auth_in mt_full_auth_in;
        
        public si_full_auth_absRequest() {
        }
        
        public si_full_auth_absRequest(DangoteSAP3.DangoteLoginService.dt_full_auth_in mt_full_auth_in) {
            this.mt_full_auth_in = mt_full_auth_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_full_auth_absResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", Order=0)]
        public DangoteSAP3.DangoteLoginService.dt_full_auth_out mt_full_auth_out;
        
        public si_full_auth_absResponse() {
        }
        
        public si_full_auth_absResponse(DangoteSAP3.DangoteLoginService.dt_full_auth_out mt_full_auth_out) {
            this.mt_full_auth_out = mt_full_auth_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface si_full_auth_absChannel : DangoteSAP3.DangoteLoginService.si_full_auth_abs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class si_full_auth_absClient : System.ServiceModel.ClientBase<DangoteSAP3.DangoteLoginService.si_full_auth_abs>, DangoteSAP3.DangoteLoginService.si_full_auth_abs {
        
        public si_full_auth_absClient() {
        }
        
        public si_full_auth_absClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public si_full_auth_absClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_full_auth_absClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_full_auth_absClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DangoteSAP3.DangoteLoginService.si_full_auth_absResponse DangoteSAP3.DangoteLoginService.si_full_auth_abs.si_full_auth_abs(DangoteSAP3.DangoteLoginService.si_full_auth_absRequest request) {
            return base.Channel.si_full_auth_abs(request);
        }
        
        public DangoteSAP3.DangoteLoginService.dt_full_auth_out si_full_auth_abs(DangoteSAP3.DangoteLoginService.dt_full_auth_in mt_full_auth_in) {
            DangoteSAP3.DangoteLoginService.si_full_auth_absRequest inValue = new DangoteSAP3.DangoteLoginService.si_full_auth_absRequest();
            inValue.mt_full_auth_in = mt_full_auth_in;
            DangoteSAP3.DangoteLoginService.si_full_auth_absResponse retVal = ((DangoteSAP3.DangoteLoginService.si_full_auth_abs)(this)).si_full_auth_abs(inValue);
            return retVal.mt_full_auth_out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteLoginService.si_full_auth_absResponse> DangoteSAP3.DangoteLoginService.si_full_auth_abs.si_full_auth_absAsync(DangoteSAP3.DangoteLoginService.si_full_auth_absRequest request) {
            return base.Channel.si_full_auth_absAsync(request);
        }
        
        public System.Threading.Tasks.Task<DangoteSAP3.DangoteLoginService.si_full_auth_absResponse> si_full_auth_absAsync(DangoteSAP3.DangoteLoginService.dt_full_auth_in mt_full_auth_in) {
            DangoteSAP3.DangoteLoginService.si_full_auth_absRequest inValue = new DangoteSAP3.DangoteLoginService.si_full_auth_absRequest();
            inValue.mt_full_auth_in = mt_full_auth_in;
            return ((DangoteSAP3.DangoteLoginService.si_full_auth_abs)(this)).si_full_auth_absAsync(inValue);
        }
    }
}
