//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangoteSAP3.DangoteResetPasswordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", ConfigurationName="DangoteResetPasswordService.si_pass_reset_abs")]
    public interface si_pass_reset_abs {
        
        // CODEGEN: Generating message contract since the operation si_pass_reset_abs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse si_pass_reset_abs(DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse> si_pass_reset_absAsync(DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_pass_rest_in : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string new_passwordField;
        
        private string new_password_confirmationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string new_password {
            get {
                return this.new_passwordField;
            }
            set {
                this.new_passwordField = value;
                this.RaisePropertyChanged("new_password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string new_password_confirmation {
            get {
                return this.new_password_confirmationField;
            }
            set {
                this.new_password_confirmationField = value;
                this.RaisePropertyChanged("new_password_confirmation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_pass_rest_out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string messageField;
        
        private dt_pass_rest_outLines[] error_logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_pass_rest_outLines[] error_log {
            get {
                return this.error_logField;
            }
            set {
                this.error_logField = value;
                this.RaisePropertyChanged("error_log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:dangote-group.com:ng:isop:authentication")]
    public partial class dt_pass_rest_outLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_pass_reset_absRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", Order=0)]
        public DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_in mt_pass_rest_in;
        
        public si_pass_reset_absRequest() {
        }
        
        public si_pass_reset_absRequest(DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_in mt_pass_rest_in) {
            this.mt_pass_rest_in = mt_pass_rest_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_pass_reset_absResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:dangote-group.com:ng:isop:authentication", Order=0)]
        public DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_out mt_pass_rest_out;
        
        public si_pass_reset_absResponse() {
        }
        
        public si_pass_reset_absResponse(DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_out mt_pass_rest_out) {
            this.mt_pass_rest_out = mt_pass_rest_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface si_pass_reset_absChannel : DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class si_pass_reset_absClient : System.ServiceModel.ClientBase<DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs>, DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs {
        
        public si_pass_reset_absClient() {
        }
        
        public si_pass_reset_absClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public si_pass_reset_absClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_pass_reset_absClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public si_pass_reset_absClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs.si_pass_reset_abs(DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest request) {
            return base.Channel.si_pass_reset_abs(request);
        }
        
        public DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_out si_pass_reset_abs(DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_in mt_pass_rest_in) {
            DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest inValue = new DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest();
            inValue.mt_pass_rest_in = mt_pass_rest_in;
            DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse retVal = ((DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs)(this)).si_pass_reset_abs(inValue);
            return retVal.mt_pass_rest_out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse> DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs.si_pass_reset_absAsync(DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest request) {
            return base.Channel.si_pass_reset_absAsync(request);
        }
        
        public System.Threading.Tasks.Task<DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absResponse> si_pass_reset_absAsync(DangoteSAP3.DangoteResetPasswordService.dt_pass_rest_in mt_pass_rest_in) {
            DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest inValue = new DangoteSAP3.DangoteResetPasswordService.si_pass_reset_absRequest();
            inValue.mt_pass_rest_in = mt_pass_rest_in;
            return ((DangoteSAP3.DangoteResetPasswordService.si_pass_reset_abs)(this)).si_pass_reset_absAsync(inValue);
        }
    }
}
